name: Run Pipeline

on:
  push:
    branches: [ "feat/actions" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      DIRECTORY_SRC: directory_scraper/src

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'directory_scraper/setup.py') }}
          restore-keys: |
             ${{ runner.os }}-pip-
                
      - name: Install package setup.py in editable mode
        run: pip install -e directory_scraper/

      - name: Run spiders and store raw data in data/spiders_output
        run: python $DIRECTORY_SRC/data_processing/run_spiders.py jpm

      - name: Upload spider output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: spider-output
          path: $DIRECTORY_SRC/data_processing/spiders_output
          retention-days: 5
