name: Fetch Google Sheets and Load to ES

on:
  push:
    branches: [ "feat/gha-main_gsheet_to_espy" ]
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      TZ: Asia/Kuala_Lumpur
      DIRECTORY_SRC: directory_scraper/src
      ES_INDEX: ${{ vars.ES_INDEX }}
      ES_SHA_INDEX: ${{ vars.ES_SHA_INDEX}}
      ES_URL: ${{ vars.ES_URL }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'directory_scraper/setup.py') }}
          restore-keys: |
             ${{ runner.os }}-pip-

      - name: Install package setup.py in editable mode
        run: pip install -e directory_scraper/

      - name: Run main
        env:
          ES_API_KEY: ${{ secrets.ES_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          THREAD_ID: ${{ secrets.THREAD_ID }}
          GSHEET_ID_MAPPING: ${{ secrets.GSHEET_ID_MAPPING }} 
          GOOGLE_SERVICE_ACCOUNT_CREDS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS }} 
        run: timeout 1000 python $DIRECTORY_SRC/workflows/main_gsheet_to_es.py # timeout (seconds)
        continue-on-error: true

      - name: Upload gsheet data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsheet_output
          path: ${{ github.workspace}}/directory_scraper/src/workflows/data/gsheet_output
          retention-days: 5

      - name: Archive es_changes_log.json
        if: success() # Run if all previous steps succeeded
        uses: actions/upload-artifact@v4
        with:
          name: es-changes-log
          path: ${{ github.workspace }}/es_changes_log.json
          retention-days: 5
